name: Release

on: 
  release:
    types: [created]

jobs: 
  publish:
    - name: Create release binaries 

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
      - name: Generate Build artificats
        run: dotnet publish .\Tehut.UI -r win-x64 /p:IncludeNativeLibrariesForSelfExtract=true --output .
      - name: Upload artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.exe'


